# Generated by Django 4.2.7 on 2024-01-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningmodel",
            name="hiperparams",
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="epochs",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="lr",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="miuo_score",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="top1_score",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="top5_score",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="val_set_size",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="learningmodel",
            name="weight_decay",
            field=models.FloatField(null=True),
        ),
    ]
