# Generated by Django 4.2.7 on 2024-01-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_learningmodel_hiperparams_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningmodel",
            old_name="miuo_score",
            new_name="miou_score",
        ),
    ]
